import type { Metadata } from "next";
import styles from "@/app/pages/pages.module.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <nav className={styles.nav}>
        <Link className={styles.link} href="/pages/about">
          about
        </Link>
        <Link className={styles.link} href="/pages/users">
          users
        </Link>
      </nav>
      <div className={styles.contain}>{children}</div>
    </main>
  );
}
